### ISSUE TITLE
SimpleMovingAverageExample

### ISSUE THREAD

**Issue by rroels** [ishanthilina/TA-Lib-Java-Examples#1]
Thanks for the example, it helped me to get things running quickly.

However, I'd like to point out a small issue in the SimpleMovingAverageExample.

Line 35 is currently:
`for (int i = begin.value; i <= length.value; i++) {`

but it should be:
`for (int i = begin.value; i < begin.value + length.value; i++) {`

"length" contains the amount of results, and not the index of the last result.

**Comment by ishanthilina** [comment]
Hey, Good catch!

Can you create a pull request?

**Comment by ishanthilina** [comment]
Fixed with Pull request #2
